### ISSUE TITLE
Feature Request - Reminder Notifications

### ISSUE THREAD

**Issue by Nergy101** [Futureglobe/Gibu_IssueTracker#2]
Hello Futureglobe,

I loved the idea of a GitHub back-up maker and I'm liking Gibu so far!

It would be even greater if it were possible to set a monthly/2 weekly reminder for creating a Back-Up.

I'm wondering if that would be possible =)

Anyhow, have a nice one!
- Nergy101 / Chris

**Comment by Futureglobe** [comment]
Hello @Nergy101,

thank you for your feature request. 
we discussed your feature request. with the team and decided to add it to the todo list. 
We are currently working on major changes so it may take a while until this feature is released with an update. We thank you for your patience.

Your Futureglobe Support Team
